In [1]:
import numpy as np
import pandas as pd

# Preparing the Data

In [2]:
df = pd.read_csv("ai_ds_job_salaries_2026_raw.csv")

df.head()

,job_title,experience_level,employment_type,company_size,company_location,industry,remote_ratio,years_experience,education_level,primary_language,team_size,certifications_count,uses_ai_tools_daily,ai_tools_hours_per_week,salary_usd
0,Data Analyst,Lead,Part-time,S,IN,Finance,0,14.4,Bachelors,Python,5,0,True,12.5,23844
1,Research Scientist,Senior,Full-time,L,US,Retail,50,7.6,Masters,SQL,6,1,False,2.1,170132
2,Machine Learning Engineer,Entry,Full-time,M,US,Government,0,0.0,Bootcamp,Python,4,1,True,5.1,83059
3,Data Engineer,Senior,Full-time,M,BR,Government,100,9.7,Masters,Java,6,2,True,2.0,29531
4,Data Engineer,Mid,Full-time,M,US,Education,0,3.2,Bachelors,Python,13,2,False,4.0,70105

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5025 entries, 0 to 5024
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   job_title                5025 non-null   object
 1   experience_level         5025 non-null   object
 2   employment_type          5025 non-null   object
 3   company_size             5025 non-null   object
 4   company_location         5025 non-null   object
 5   industry                 5025 non-null   object
 6   remote_ratio             5025 non-null   int64
 7   years_experience         4975 non-null   float64
 8   education_level          4975 non-null   object
 9   primary_language         4975 non-null   object
 10  team_size                5025 non-null   int64
 11  certifications_count     5025 non-null   int64
 12  uses_ai_tools_daily      5025 non-null   bool
 13  ai_tools_hours_per_week  5025 non-null   float64
 14  salary_usd               5025 non-null   int64
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 554.6+ KB

In [4]:
df.describe()

,remote_ratio,years_experience,team_size,certifications_count,ai_tools_hours_per_week,salary_usd
count,5025.000000,4975.000000,5025.000000,5025.000000,5025.000000,5025.000000
mean,43.064677,8.364884,8.129950,1.824080,8.427144,98631.556020
std,41.459740,4.836308,14.244608,1.368178,5.498547,55353.120506
min,0.000000,-2.000000,-5.000000,-1.000000,0.000000,12000.000000
25%,0.000000,4.800000,6.000000,1.000000,3.300000,55672.000000
50%,50.000000,8.100000,8.000000,2.000000,8.500000,90598.000000
75%,100.000000,11.500000,10.000000,3.000000,12.600000,129611.000000
max,100.000000,35.000000,1000.000000,20.000000,25.200000,372347.000000

In [5]:
df.isnull().sum

<bound method DataFrame.sum of       job_title  experience_level  employment_type  company_size  \
0         False             False            False         False
1         False             False            False         False
2         False             False            False         False
3         False             False            False         False
4         False             False            False         False
...         ...               ...              ...           ...
5020      False             False            False         False
5021      False             False            False         False
5022      False             False            False         False
5023      False             False            False         False
5024      False             False            False         False

      company_location  industry  remote_ratio  years_experience  \
0                False     False         False             False
1                False     False         False             False
2                False     False         False             False
3                False     False         False             False
4                False     False         False             False
...                ...       ...           ...               ...
5020             False     False         False             False
5021             False     False         False             False
5022             False     False         False             False
5023             False     False         False             False
5024             False     False         False             False

      education_level  primary_language  team_size  certifications_count  \
0               False             False      False                 False
1               False             False      False                 False
2               False             False      False                 False
3               False             False      False                 False
4               False             False      False                 False
...               ...               ...        ...                   ...
5020            False             False      False                 False
5021            False             False      False                 False
5022            False             False      False                 False
5023            False             False      False                 False
5024            False             False      False                 False

      uses_ai_tools_daily  ai_tools_hours_per_week  salary_usd
0                   False                    False       False
1                   False                    False       False
2                   False                    False       False
3                   False                    False       False
4                   False                    False       False
...                   ...                      ...         ...
5020                False                    False       False
5021                False                    False       False
5022                False                    False       False
5023                False                    False       False
5024                False                    False       False

[5025 rows x 15 columns]>

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df = df.replace(r'^\s*$', np.nan, regex=True)

In [8]:
df.duplicated().sum()

np.int64(25)

In [9]:
df[df.duplicated(keep=False)]

,job_title,experience_level,employment_type,company_size,company_location,industry,remote_ratio,years_experience,education_level,primary_language,team_size,certifications_count,uses_ai_tools_daily,ai_tools_hours_per_week,salary_usd
32,Analytics Engineer,Senior,Full-time,L,IN,Healthcare,0,11.2,Bootcamp,R,6,4,True,4.2,39008
89,Business Intelligence Analyst,Mid,Full-time,L,DE,Finance,0,7.1,Masters,Python,2,1,True,5.7,74355
527,Data Science Manager,Senior,Contract,S,US,Manufacturing,0,9.3,Masters,SQL,8,3,True,1.9,119992
545,AI Engineer,Mid,Full-time,L,FR,Manufacturing,100,5.9,Self-taught,Python,6,3,True,10.4,77092
699,MLOps Engineer,Mid,Full-time,M,US,Manufacturing,100,8.4,Bachelors,Python,4,1,False,0.0,101952
737,Research Scientist,Lead,Full-time,M,SG,Consulting,50,15.4,Bachelors,Python,8,2,True,12.6,164051
827,Research Scientist,Mid,Full-time,L,GB,Technology,100,8.0,Masters,SQL,14,1,False,3.5,119950
905,Computer Vision Engineer,Senior,Full-time,S,PL,Technology,0,12.2,Masters,SQL,5,5,False,2.8,75193
2088,Data Scientist,Senior,Contract,S,NL,Manufacturing,0,9.8,Masters,Python,9,2,False,5.8,129465
2157,Business Intelligence Analyst,Mid,Contract,M,DE,Media,100,7.7,Masters,Python,12,1,True,9.4,70850
2334,Data Science Manager,Mid,Full-time,L,US,Media,0,6.3,Self-taught,SQL,10,1,True,5.8,175091
2762,Research Scientist,Mid,Full-time,L,PL,Healthcare,0,8.8,PhD,Python,8,2,True,8.9,76203
2973,AI Engineer,Mid,Full-time,S,US,Technology,100,4.2,Bachelors,Python,5,2,False,1.2,113000
3155,Data Science Manager,Mid,Full-time,S,IN,Finance,0,3.8,PhD,SQL,4,3,False,0.2,34557
3168,Machine Learning Engineer,Senior,Full-time,L,US,Finance,0,10.3,Masters,Python,10,4,True,6.9,197711
3317,Data Scientist,Senior,Part-time,M,PL,Technology,0,8.4,Bachelors,Python,8,1,False,3.5,42308
3602,Machine Learning Engineer,Mid,Full-time,L,CA,Healthcare,50,4.9,Masters,Python,6,2,True,11.9,125638
3684,Business Intelligence Analyst,Mid,Full-time,L,IN,Technology,50,7.5,Masters,Python,11,3,True,11.4,29372
3731,LLM Engineer,Mid,Full-time,M,US,Consulting,50,8.5,Bachelors,Python,9,0,False,6.4,108572
3920,AI Engineer,Entry,Full-time,L,ES,Healthcare,100,0.7,PhD,SQL,8,0,True,10.8,48412
4015,Data Scientist,Lead,Full-time,S,CA,Finance,50,14.4,Bachelors,R,10,2,True,4.4,118361
4186,Data Scientist,Entry,Full-time,M,US,Healthcare,0,2.1,Masters,Python,5,1,True,8.1,77553
4232,Machine Learning Engineer,Lead,Full-time,L,AU,Healthcare,0,16.4,Bootcamp,R,10,1,False,2.2,159352
4655,Data Science Manager,Executive,Full-time,M,US,Manufacturing,50,20.5,Bootcamp,R,11,2,True,9.8,236341
4817,AI Engineer,Entry,Full-time,M,AU,Finance,100,1.2,Bachelors,SQL,6,1,True,11.6,82159
5000,Data Science Manager,Executive,Full-time,M,US,Manufacturing,50,20.5,Bootcamp,R,11,2,True,9.8,236341
5001,Data Scientist,Senior,Contract,S,NL,Manufacturing,0,9.8,Masters,Python,9,2,False,5.8,129465
5002,AI Engineer,Entry,Full-time,M,AU,Finance,100,1.2,Bachelors,SQL,6,1,True,11.6,82159
5003,Business Intelligence Analyst,Mid,Full-time,L,DE,Finance,0,7.1,Masters,Python,2,1,True,5.7,74355
5004,Research Scientist,Mid,Full-time,L,PL,Healthcare,0,8.8,PhD,Python,8,2,True,8.9,76203
5005,Research Scientist,Mid,Full-time,L,GB,Technology,100,8.0,Masters,SQL,14,1,False,3.5,119950
5006,Data Science Manager,Mid,Full-time,L,US,Media,0,6.3,Self-taught,SQL,10,1,True,5.8,175091
5007,Data Science Manager,Mid,Full-time,S,IN,Finance,0,3.8,PhD,SQL,4,3,False,0.2,34557
5008,Research Scientist,Lead,Full-time,M,SG,Consulting,50,15.4,Bachelors,Python,8,2,True,12.6,164051
5009,Data Scientist,Senior,Part-time,M,PL,Technology,0,8.4,Bachelors,Python,8,1,False,3.5,42308
5010,Data Scientist,Entry,Full-time,M,US,Healthcare,0,2.1,Masters,Python,5,1,True,8.1,77553
5011,AI Engineer,Mid,Full-time,L,FR,Manufacturing,100,5.9,Self-taught,Python,6,3,True,10.4,77092
5012,Business Intelligence Analyst,Mid,Full-time,L,IN,Technology,50,7.5,Masters,Python,11,3,True,11.4,29372
5013,AI Engineer,Mid,Full-time,S,US,Technology,100,4.2,Bachelors,Python,5,2,False,1.2,113000
5014,Data Scientist,Lead,Full-time,S,CA,Finance,50,14.4,Bachelors,R,10,2,True,4.4,118361
5015,Machine Learning Engineer,Lead,Full-time,L,AU,Healthcare,0,16.4,Bootcamp,R,10,1,False,2.2,159352
5016,Computer Vision Engineer,Senior,Full-time,S,PL,Technology,0,12.2,Masters,SQL,5,5,False,2.8,75193
5017,AI Engineer,Entry,Full-time,L,ES,Healthcare,100,0.7,PhD,SQL,8,0,True,10.8,48412
5018,MLOps Engineer,Mid,Full-time,M,US,Manufacturing,100,8.4,Bachelors,Python,4,1,False,0.0,101952
5019,Data Science Manager,Senior,Contract,S,US,Manufacturing,0,9.3,Masters,SQL,8,3,True,1.9,119992
5020,Analytics Engineer,Senior,Full-time,L,IN,Healthcare,0,11.2,Bootcamp,R,6,4,True,4.2,39008
5021,Business Intelligence Analyst,Mid,Contract,M,DE,Media,100,7.7,Masters,Python,12,1,True,9.4,70850
5022,Machine Learning Engineer,Mid,Full-time,L,CA,Healthcare,50,4.9,Masters,Python,6,2,True,11.9,125638
5023,Machine Learning Engineer,Senior,Full-time,L,US,Finance,0,10.3,Masters,Python,10,4,True,6.9,197711
5024,LLM Engineer,Mid,Full-time,M,US,Consulting,50,8.5,Bachelors,Python,9,0,False,6.4,108572

# Filling Null values in years_experience Column

In [10]:
df['years_experience'].fillna(df['years_experience'].mean(), inplace=True)

C:\Users\Almagd\AppData\Local\Temp\ipykernel_16136\4080351228.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['years_experience'].fillna(df['years_experience'].mean(), inplace=True)

In [11]:
minus = df['years_experience'] < 0
minus.sum()

np.int64(2)

In [12]:
df.loc[df["years_experience"] < 0, "years_experience"] = 0

In [13]:
minus = df['years_experience'] < 0
minus.sum()

np.int64(0)

In [14]:
df["years_experience"] = df["years_experience"].round().astype("int")

# Filling Null values in education_level Column

In [15]:
df['education_level'].isnull().sum()

np.int64(50)

In [16]:
df['education_level'] = df['education_level'].fillna('Unknown')

In [17]:
df['education_level'].isnull().sum()

np.int64(0)

# Filling Null values in primary_language Column

In [18]:
df['primary_language'].isnull().sum()

np.int64(50)

In [19]:
df['primary_language'] = df['primary_language'].fillna('Python')

In [20]:
df['primary_language'].isnull().sum()

np.int64(0)

# Converting data type

In [21]:
df["ai_tools_hours_per_week"] = df["ai_tools_hours_per_week"].round().astype("int")

# Invalid Team Size

In [22]:
minus = df['team_size'] < 0
minus.sum()

np.int64(1)

In [23]:
minus1 = df['team_size'] > 100
minus1.sum()

np.int64(1)

In [24]:
df['team_size'].median()

8.0

In [25]:
df.loc[df["team_size"] < 0, "team_size"] = df['team_size'].median()
df.loc[df["team_size"] > 100, "team_size"] = df['team_size'].median()

In [26]:
minus = df['team_size'] < 0
minus.sum()

np.int64(0)

In [27]:
minus1 = df['team_size'] > 100
minus1.sum()

np.int64(0)

# Invalid Certifications

In [28]:
df.loc[(df["certifications_count"] < 0) | (df["certifications_count"] > 10), "certifications_count"] = np.nan

In [29]:
df["certifications_count"] = df["certifications_count"].fillna(df["certifications_count"].median())

In [30]:
df["certifications_count"] = df["certifications_count"].round().astype("int")

# Remove Duplicates

In [31]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 25
Duplicates after: 0

In [32]:
df.shape

(5000, 15)

# Unique Values

In [33]:
df.nunique()

job_title                    12
experience_level             10
employment_type               4
company_size                  6
company_location             12
industry                     10
remote_ratio                  3
years_experience             26
education_level              11
primary_language              7
team_size                    19
certifications_count          9
uses_ai_tools_daily           2
ai_tools_hours_per_week      26
salary_usd                 4928
dtype: int64

In [34]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

unique_values = df.apply(lambda col: col.unique())
print(unique_values)

job_title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [Data Analyst, Research Scientist, Machine Learning Engineer, Data Engineer, Analytics Engineer, Business Intelligence Analyst, Data Science Manager, Computer Vision Engineer, LLM Engineer, Data Scientist, AI Engineer, MLOps Engineer]
experience_level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [Lead, Senior, Entry, Mid, Executive,  Senior ,  Lead ,  Executive ,  Mid ,  Entry ]
employment_type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [Part-time, Full-time, Contract, Freelance]
company_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [S, L, M,  S ,  L ,  M ]
company_location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [IN, US, BR, SG, AU, GB, FR, DE, PL, NL, CA, ES]
industry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [Finance, Retail, Government, Education, Technology, Healthcare, Consulting, Media, Manufacturing, Energy]
remote_ratio                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [0, 50, 100]
years_experience                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [14, 8, 0, 10, 3, 12, 1, 2, 7, 4, 9, 5, 6, 11, 16, 15, 17, 13, 21, 18, 20, 22, 19, 23, 35, 24]
education_level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [Bachelors, Masters, Bootcamp, Self-taught, PhD,  Masters , Unknown,  Bootcamp ,  Bachelors ,  PhD ,  Self-taught ]
primary_language                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [Python, SQL, Java, R, Julia, Scala, Rust]
team_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [5, 6, 4, 13, 9, 11, 12, 8, 7, 10, 14, 18, 2, 15, 3, 1, 17, 16, 19]
certifications_count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [0, 1, 2, 3, 4, 6, 5, 8, 7]
uses_ai_tools_daily                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [True, False]
ai_tools_hours_per_week                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [12, 2, 5, 4, 17, 0, 7, 8, 3, 14, 10, 1, 18, 9, 13, 11, 25, 6, 15, 23, 20, 19, 16, 21, 24, 22]
salary_usd                 [23844, 170132, 83059, 29531, 70105, 97827, 120062, 64165, 112968, 26464, 188326, 112063, 60087, 75169, 123386, 61792, 121126, 127602, 24899, 29902, 267112, 95682, 32162, 24840, 128115, 47620, 47829, 221527, 95058, 93560, 49555, 30459, 39008, 24260, 113587, 63639, 38694, 45726, 45653, 139305, 53183, 76753, 135285, 34110, 172487, 69827, 91428, 20358, 47335, 151394, 195720, 29965, 276910, 104896, 83238, 38007, 169730, 179645, 120239, 60384, 245491, 84140, 99236, 20350, 97474, 81977, 197149, 179885, 49581, 145188, 48644, 128061, 103751, 47457, 36703, 84722, 20211, 204902, 94426, 213117, 191241, 47234, 90333, 67204, 88207, 85637, 63446, 92547, 169313, 74355, 207529, 29779, 89600, 87299, 124075, 132418, 214002, 223581, 28979, 203974, ...]
dtype: object

In [35]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

In [36]:
df.nunique()

job_title                    12
experience_level              5
employment_type               4
company_size                  3
company_location             12
industry                     10
remote_ratio                  3
years_experience             26
education_level               6
primary_language              7
team_size                    19
certifications_count          9
uses_ai_tools_daily           2
ai_tools_hours_per_week      26
salary_usd                 4928
dtype: int64

In [37]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

unique_values = df.apply(lambda col: col.unique())
print(unique_values)

job_title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [Data Analyst, Research Scientist, Machine Learning Engineer, Data Engineer, Analytics Engineer, Business Intelligence Analyst, Data Science Manager, Computer Vision Engineer, LLM Engineer, Data Scientist, AI Engineer, MLOps Engineer]
experience_level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [Lead, Senior, Entry, Mid, Executive]
employment_type                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [Part-time, Full-time, Contract, Freelance]
company_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [S, L, M]
company_location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [IN, US, BR, SG, AU, GB, FR, DE, PL, NL, CA, ES]
industry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [Finance, Retail, Government, Education, Technology, Healthcare, Consulting, Media, Manufacturing, Energy]
remote_ratio                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [0, 50, 100]
years_experience                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [14, 8, 0, 10, 3, 12, 1, 2, 7, 4, 9, 5, 6, 11, 16, 15, 17, 13, 21, 18, 20, 22, 19, 23, 35, 24]
education_level                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [Bachelors, Masters, Bootcamp, Self-taught, PhD, Unknown]
primary_language                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [Python, SQL, Java, R, Julia, Scala, Rust]
team_size                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [5, 6, 4, 13, 9, 11, 12, 8, 7, 10, 14, 18, 2, 15, 3, 1, 17, 16, 19]
certifications_count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [0, 1, 2, 3, 4, 6, 5, 8, 7]
uses_ai_tools_daily                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [True, False]
ai_tools_hours_per_week                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             [12, 2, 5, 4, 17, 0, 7, 8, 3, 14, 10, 1, 18, 9, 13, 11, 25, 6, 15, 23, 20, 19, 16, 21, 24, 22]
salary_usd                 [23844, 170132, 83059, 29531, 70105, 97827, 120062, 64165, 112968, 26464, 188326, 112063, 60087, 75169, 123386, 61792, 121126, 127602, 24899, 29902, 267112, 95682, 32162, 24840, 128115, 47620, 47829, 221527, 95058, 93560, 49555, 30459, 39008, 24260, 113587, 63639, 38694, 45726, 45653, 139305, 53183, 76753, 135285, 34110, 172487, 69827, 91428, 20358, 47335, 151394, 195720, 29965, 276910, 104896, 83238, 38007, 169730, 179645, 120239, 60384, 245491, 84140, 99236, 20350, 97474, 81977, 197149, 179885, 49581, 145188, 48644, 128061, 103751, 47457, 36703, 84722, 20211, 204902, 94426, 213117, 191241, 47234, 90333, 67204, 88207, 85637, 63446, 92547, 169313, 74355, 207529, 29779, 89600, 87299, 124075, 132418, 214002, 223581, 28979, 203974, ...]
dtype: object

# Categorical Values

In [38]:
categorical_cols = df.select_dtypes(include="object").columns

with pd.option_context("display.max_rows", None):
    for col in categorical_cols:
        print(f"\n--- {col} ---")
        display(df[col].value_counts())

--- job_title ---

job_title
Data Scientist                   709
Data Engineer                    682
Data Analyst                     627
Machine Learning Engineer        593
AI Engineer                      506
Analytics Engineer               317
MLOps Engineer                   306
Business Intelligence Analyst    293
Research Scientist               269
LLM Engineer                     242
Data Science Manager             238
Computer Vision Engineer         218
Name: count, dtype: int64

--- experience_level ---

experience_level
Mid          1613
Senior       1520
Entry         985
Lead          656
Executive     226
Name: count, dtype: int64

--- employment_type ---

employment_type
Full-time    4159
Contract      418
Freelance     212
Part-time     211
Name: count, dtype: int64

--- company_size ---

company_size
M    2551
L    1288
S    1161
Name: count, dtype: int64

--- company_location ---

company_location
US    1786
IN     782
GB     488
DE     350
CA     350
AU     240
BR     210
NL     200
FR     189
PL     147
SG     130
ES     128
Name: count, dtype: int64

--- industry ---

industry
Technology       1528
Finance           839
Healthcare        543
Retail            452
Consulting        442
Manufacturing     302
Media             268
Government        254
Education         196
Energy            176
Name: count, dtype: int64

--- education_level ---

education_level
Bachelors      1882
Masters        1774
PhD             530
Bootcamp        467
Self-taught     297
Unknown          50
Name: count, dtype: int64

--- primary_language ---

primary_language
Python    3146
SQL        912
R          287
Java       256
Scala      219
Julia      102
Rust        78
Name: count, dtype: int64

# Adding Country Name

In [39]:
country_map = {
    "US": "United States",
    "IN": "India",
    "GB": "Great Britain",
    "DE": "Germany",
    "CA": "Canada",
    "AU": "Australia",
    "BR": "Brazil",
    "NL": "Netherlands",
    "FR": "France",
    "PL": "Poland",
    "SG": "Singapore",
    "ES": "Spain",
}

df["company_location_name"] = df["company_location"].map(country_map)
df = df.drop("company_location", axis=1)

In [40]:
col_to_move = df.pop("company_location_name")
target_idx = df.columns.get_loc("industry")
df.insert(target_idx + 1, "company_location_name", col_to_move)

# Reset Index

In [41]:
df = df.reset_index(drop=True)

# Ensuring the Data

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   job_title                5000 non-null   object
 1   experience_level         5000 non-null   object
 2   employment_type          5000 non-null   object
 3   company_size             5000 non-null   object
 4   industry                 5000 non-null   object
 5   company_location_name    5000 non-null   object
 6   remote_ratio             5000 non-null   int64
 7   years_experience         5000 non-null   int64
 8   education_level          5000 non-null   object
 9   primary_language         5000 non-null   object
 10  team_size                5000 non-null   int64
 11  certifications_count     5000 non-null   int64
 12  uses_ai_tools_daily      5000 non-null   bool
 13  ai_tools_hours_per_week  5000 non-null   int64
 14  salary_usd               5000 non-null   int64
dtypes: bool(1), int64(6), object(8)
memory usage: 551.9+ KB

In [43]:
df.describe()

,remote_ratio,years_experience,team_size,certifications_count,ai_tools_hours_per_week,salary_usd
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,43.08000,8.360000,7.935800,1.820600,8.428400,98605.406200
std,41.45428,4.826288,2.647769,1.343866,5.517804,55369.310473
min,0.00000,0.000000,1.000000,0.000000,0.000000,12000.000000
25%,0.00000,5.000000,6.000000,1.000000,3.000000,55592.750000
50%,50.00000,8.000000,8.000000,2.000000,8.000000,90572.000000
75%,100.00000,12.000000,10.000000,3.000000,13.000000,129657.750000
max,100.00000,35.000000,19.000000,8.000000,25.000000,372347.000000

# Data is CLEAN !!!

In [44]:
df.to_csv("ai_ds_job_salaries_2026_cleaned.csv", index=False)

print(f"Saved {len(df):,} rows to ai_ds_job_salaries_2026_cleaned.csv")

Saved 5,000 rows to ai_ds_job_salaries_2026_cleaned.csv